export const optimizedPhotos = [
  {
    id: 1,
    src: "/images/hero/hero-zameczek-lato.jpeg",
    alt: "Zameczek Bukowiec – widok z zewnątrz, lato",
    category: "budynek",
  },
  {
    id: 2,
    src: "/images/hero/hero-zameczek-zima.jpeg",
    alt: "Zameczek Bukowiec – widok z zewnątrz, zima",
    category: "budynek",
  },
  {
    id: 3,
    src: "/images/about/ogrod-drzewo-hustawka-jesien.jpeg",
    alt: "Ogród z huśtawką i wielkim drzewem jesienią",
    category: "okolica",
  },
  {
    id: 4,
    src: "/images/about/ogrod-widok-gory-jesien.jpeg",
    alt: "Widok z ogrodu na jesienne wzgórza",
    category: "okolica",
  },
  {
    id: 5,
    src: "/images/about/ogrod-altana-grill.jpeg",
    alt: "Altanka z grillem w ogrodzie",
    category: "okolica",
  },
  {
    id: 6,
    src: "/images/about/ogrod-widok-rzeka-jesien.jpeg",
    alt: "Widok z ogrodu na rzekę i jesienne wzgórza",
    category: "okolica",
  },
  {
    id: 7,
    src: "/images/rooms/pokoj-chesterfield-lozko.jpeg",
    alt: "Pokój z łóżkiem chesterfield",
    category: "pokoje",
  },
  {
    id: 8,
    src: "/images/rooms/pokoj-chesterfield-widok1.jpeg",
    alt: "Pokój z łóżkiem chesterfield – widok na okno",
    category: "pokoje",
  },
  {
    id: 9,
    src: "/images/rooms/pokoj-granatowy-lozko.jpeg",
    alt: "Pokój z granatowym łóżkiem",
    category: "pokoje",
  },
  {
    id: 10,
    src: "/images/rooms/salon-kanapa-kominek-widok.jpeg",
    alt: "Salon z kanapą i kominkiem",
    category: "wnetrza",
  },
  {
    id: 11,
    src: "/images/rooms/salon-kanapa-widok1.jpeg",
    alt: "Salon z dużą kanapą i łukowymi oknami",
    category: "wnetrza",
  },
  {
    id: 12,
    src: "/images/rooms/salon-kanapa-kominek-panorama.jpeg",
    alt: "Panorama salonu z kominkiem",
    category: "wnetrza",
  },
  {
    id: 13,
    src: "/images/rooms/jadalnia-stol-okna-lukowe1.jpeg",
    alt: "Jadalnia w wieżyczce z oknami łukowymi",
    category: "wnetrza",
  },
  {
    id: 14,
    src: "/images/rooms/jadalnia-stol-okna-lukowe2.jpeg",
    alt: "Jadalnia w wieżyczce – inny kąt",
    category: "wnetrza",
  },
  {
    id: 15,
    src: "/images/rooms/jadalnia-kuchnia-panorama.jpeg",
    alt: "Widok na jadalnię i kuchnię przez arkadę",
    category: "wnetrza",
  },
  {
    id: 16,
    src: "/images/rooms/kuchnia-zabudowa1.jpeg",
    alt: "Kuchnia z zabudową drewnianą",
    category: "wnetrza",
  },
  {
    id: 17,
    src: "/images/rooms/kuchnia-zabudowa2.jpeg",
    alt: "Kuchnia – inny kąt",
    category: "wnetrza",
  },
  {
    id: 18,
    src: "/images/rooms/kuchnia-piekarnik-lodowka.jpeg",
    alt: "Kuchnia z piekarnikiem i lodówką",
    category: "wnetrza",
  },
  {
    id: 19,
    src: "/images/about/okolica-droga-gory-jesien.jpeg",
    alt: "Droga w okolicy z widokiem na jesienne góry",
    category: "okolica",
  },
  {
    id: 20,
    src: "/images/gallery/galeria-01.jpeg",
    alt: "Zameczek Bukowiec – galeria 1",
    category: "pokoje",
  },
  {
    id: 21,
    src: "/images/gallery/galeria-02.jpeg",
    alt: "Zameczek Bukowiec – galeria 2",
    category: "pokoje",
  },
  {
    id: 22,
    src: "/images/gallery/galeria-03.jpeg",
    alt: "Zameczek Bukowiec – galeria 3",
    category: "pokoje",
  },
  {
    id: 23,
    src: "/images/gallery/galeria-04.jpeg",
    alt: "Zameczek Bukowiec – galeria 4",
    category: "pokoje",
  },
  {
    id: 24,
    src: "/images/gallery/galeria-05.jpeg",
    alt: "Zameczek Bukowiec – galeria 5",
    category: "pokoje",
  },
  {
    id: 25,
    src: "/images/gallery/galeria-06.jpeg",
    alt: "Zameczek Bukowiec – galeria 6",
    category: "pokoje",
  },
  {
    id: 26,
    src: "/images/gallery/galeria-07.jpeg",
    alt: "Zameczek Bukowiec – galeria 7",
    category: "pokoje",
  },
  {
    id: 27,
    src: "/images/gallery/galeria-08.jpeg",
    alt: "Zameczek Bukowiec – galeria 8",
    category: "pokoje",
  },
  {
    id: 28,
    src: "/images/gallery/galeria-09.jpeg",
    alt: "Zameczek Bukowiec – galeria 9",
    category: "pokoje",
  },
  {
    id: 29,
    src: "/images/gallery/galeria-10.jpeg",
    alt: "Zameczek Bukowiec – galeria 10",
    category: "pokoje",
  },
  {
    id: 30,
    src: "/images/gallery/galeria-11.jpeg",
    alt: "Zameczek Bukowiec – galeria 11",
    category: "pokoje",
  },
  {
    id: 31,
    src: "/images/gallery/galeria-12.jpeg",
    alt: "Zameczek Bukowiec – galeria 12",
    category: "pokoje",
  },
  {
    id: 32,
    src: "/images/gallery/galeria-13.jpeg",
    alt: "Zameczek Bukowiec – galeria 13",
    category: "pokoje",
  },
  {
    id: 33,
    src: "/images/gallery/galeria-14.jpeg",
    alt: "Zameczek Bukowiec – galeria 14",
    category: "pokoje",
  },
  {
    id: 34,
    src: "/images/gallery/galeria-15.jpeg",
    alt: "Zameczek Bukowiec – galeria 15",
    category: "pokoje",
  },
  {
    id: 35,
    src: "/images/gallery/galeria-16.jpeg",
    alt: "Zameczek Bukowiec – galeria 16",
    category: "pokoje",
  },
  {
    id: 36,
    src: "/images/gallery/galeria-17.jpeg",
    alt: "Zameczek Bukowiec – galeria 17",
    category: "pokoje",
  },
  {
    id: 37,
    src: "/images/gallery/galeria-18.jpeg",
    alt: "Zameczek Bukowiec – galeria 18",
    category: "pokoje",
  },
];
